# Generated by Django 3.2 on 2022-01-09 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_friends_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='friends',
            new_name='friends_list',
        ),
        migrations.AlterField(
            model_name='friends',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
