# Generated by Django 3.2 on 2022-01-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220109_0632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
