# Generated by Django 3.2 on 2022-01-14 16:29

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=pathlib.PurePosixPath('/home/patrick/Desktop/Projects/BudgetTracker/backend/media/defaults/images/default_avatar.png'), upload_to='', verbose_name='Avatar'),
        ),
    ]
