# Generated by Django 3.2 on 2022-01-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/home/patrick/Desktop/Projects/BudgetTracker/backend/media/defaults/images/default_avatar.png', upload_to='', verbose_name='Avatar'),
        ),
    ]
