# Generated by Django 3.2 on 2021-12-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20211225_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='budget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='income', to='budget.budget'),
        ),
    ]
