# Generated by Django 3.2 on 2021-12-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_income_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='value',
        ),
    ]
