# Generated by Django 3.2 on 2022-01-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_remove_budget_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='income',
            name='budget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='budget.budget'),
        ),
    ]
