# Generated by Django 3.2 on 2022-01-03 14:41

import budget.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20220103_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=30)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget.budget')),
                ('expense', models.ManyToManyField(to='budget.Expense')),
            ],
            options={
                'abstract': False,
            },
            bases=(budget.mixins.FullCleanSaveMixin, models.Model),
        ),
    ]
