# Generated by Django 3.2 on 2022-01-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='expense',
            field=models.ManyToManyField(blank=True, to='budget.Expense'),
        ),
    ]
