# Generated by Django 3.2 on 2022-01-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_alter_category_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='expense',
            new_name='expenses',
        ),
    ]
