# Generated by Django 3.2 on 2022-01-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_rename_expense_category_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='expenses',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.category'),
        ),
    ]
